#[Info]
site_name: Blog of GZH #your site name 显示在左上角
site_url: https://gongzihang6.github.io/
site_description: 记录、分享
site_author: gzh # your name
#[UI]
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: overrides #覆写路径
  # logo: assets/favicon.png #左上角logo，可插入图片链接

  favicon: https://s2.loli.net/2025/02/12/aE5ovtzAlNTd9Uh.png # 网页icon

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: blue # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      toggle:
        icon: material/toggle-switch # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式

  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.code.select
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    # - navigation.instant
    #- header.autohide  #自动隐藏
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
  language: zh # 一些提示性的文字会变成中文


  icon:
    repo: fontawesome/brands/github #右上角图标
    logo: logo
    previous: fontawesome/solid/angle-left
    # top: fontawesome/solid/angles-up
    alternate: fontawesome/solid/language
edit_uri: edit/main/docs # 编辑按钮跳转的链接
repo_url: https://github.com/Gongzihang6 # 右上角点击跳转的链接
repo_name: Gongzihang6 # 右上角的名字

# [Navigtion]
# 下面的.md文件以docs为根目录确定路径
nav:
  - 主页: index.md

  ################################################################################################
  # - 技术:
  #   # - index: 
  - Computer Science: 
    - Java:
      - Java面向对象基础: blog/Computer Science/java基础.md
      - Java集合框架与常用API: blog/Computer Science/常用API.md
      - Java提高: blog/Computer Science/java提高.md
      - blog/Computer Science/JavaStream流式处理方法.md
    - Algorithm:
      - 并查集:
        - blog/Computer Science/Algorithm/算法基础/ds/并查集.md
        - blog/Computer Science/Algorithm/算法基础/ds/dsu-complexity.md
      - blog/Computer Science/排序和查找.md
    - LeetCode周赛系列:
      - blog/Computer Science/LeetCode周赛系列/第467场周赛.md
      - blog/Computer Science/LeetCode周赛系列/第468场周赛.md
    - LeetCode热题100:
      - blog/Computer Science/LeetCode热题100/字母异位词分组.md
      - blog/Computer Science/LeetCode热题100/最长连续序列.md
      - blog/Computer Science/LeetCode热题100/移动零.md
      - blog/Computer Science/LeetCode热题100/盛水最多的容器.md
      - blog/Computer Science/LeetCode热题100/三数之和.md
      - blog/Computer Science/LeetCode热题100/无重复字符的最长子串.md
      - blog/Computer Science/LeetCode热题100/和为K的子数组.md
      - blog/Computer Science/LeetCode热题100/合并区间.md
      - blog/Computer Science/LeetCode热题100/矩阵置零.md
      - blog/Computer Science/LeetCode热题100/螺旋矩阵.md
      - blog/Computer Science/LeetCode热题100/旋转图像.md
    - LeetCode:
      - blog/Computer Science/LeetCode/交易逆序对的总数.md
      - blog/Computer Science/LeetCode/单词接龙.md
      - blog/Computer Science/LeetCode/岛屿数量.md
      - blog/Computer Science/LeetCode/分考场.md
      - blog/Computer Science/LeetCode/拉马车.md
      - blog/Computer Science/LeetCode/分巧克力.md
      - blog/Computer Science/LeetCode/k倍区间.md
      - blog/Computer Science/LeetCode/编辑距离.md
      - blog/Computer Science/LeetCode/接雨水.md
      - blog/Computer Science/LeetCode/组合总和.md
      - blog/Computer Science/LeetCode/全排列.md
      - blog/Computer Science/LeetCode/乘积最大子数组.md
      - blog/Computer Science/LeetCode/最长回文子串.md
      - blog/Computer Science/LeetCode/前K个高频元素.md
      - blog/Computer Science/LeetCode/最小栈.md
      - blog/Computer Science/LeetCode/Pow(x,n).md
      - blog/Computer Science/LeetCode/网络延迟时间.md
      - blog/Computer Science/LeetCode/计算质数.md
      - blog/Computer Science/LeetCode/对角线上的质数.md
      - blog/Computer Science/LeetCode/零钱兑换.md
      - blog/Computer Science/LeetCode/01矩阵.md
      - blog/Computer Science/LeetCode/二分查找.md
      - blog/Computer Science/LeetCode/括号匹配.md
      - blog/Computer Science/LeetCode/300最长递增子序列.md
      - blog/Computer Science/LeetCode/115不同的子序列.md
      - blog/Computer Science/LeetCode/712两个字符串的最小ASCII删除和.md
      - blog/Computer Science/LeetCode/516最长回文子序列.md
      - blog/Computer Science/LeetCode/139单词拆分.md
      - blog/Computer Science/LeetCode/221最大正方形.md
      - blog/Computer Science/LeetCode/2845统计趣味子数组的数目.md
      - blog/Computer Science/LeetCode/2799统计完全子数组的数目.md
      - blog/Computer Science/LeetCode/1399统计最大组的数目.md
      - blog/Computer Science/LeetCode/2338统计理想数组的数目.md
      - blog/Computer Science/LeetCode/2179统计数组中好三元组数目.md
      - blog/Computer Science/LeetCode/2537统计好子数组的数.md
      - blog/Computer Science/LeetCode/2140解决智力问题.md
      - blog/Computer Science/LeetCode/2278字母在字符串中的百分比.md


  - MachineLearning: 
    - blog/MachineLearning/K近邻学习与降维.md
    - blog/MachineLearning/模型评估与多分类.md
    - blog/MachineLearning/公式测试.md
    - blog/MachineLearning/经典卷积神经网络.md
    - blog/MachineLearning/理解YOLO网络结构.md
    - blog\MachineLearning\关联分析.md
    - blog\MachineLearning\支持向量机SVM.md
    - blog\MachineLearning\聚类算法.md
  - 随笔:
    - 科研:
      - blog/随笔/科研/摄像机成像模型.md
      - blog/随笔/科研/求解两个坐标系的相对旋转和平移矩阵.md
      - blog/随笔/科研/多相机同步采集数据.md
      - blog/随笔/科研/PCL库总结.md
      - 文献阅读: 
        - blog/随笔/科研/文献阅读/PointMamba.md
        - blog/随笔/科研/文献阅读/swin3d.md
    - 优化:
      - blog/随笔/优化/Levenberg-Marquardt算法.md
    - blog/随笔/latex入门学习.md
    - blog/随笔/Matlab基础速成.md
    - blog/随笔/Matlab进阶.md
    - blog/随笔/Py-Markdown.md
    - blog/随笔/ssh_gitlab.md
    - blog/随笔/2024年秋招-小米集团-软件开发岗-第一批笔试.md
    - blog\随笔\cmd_powershell_bash.md
    - blog\随笔\正则表达式.md
    - blog/随笔/对注解Autowired的理解.md
    - blog/随笔/http状态码含义以及对应解决方案.md
    - blog/随笔/element-plus组件理解.md
    - blog/随笔/SpringBoot注解总结.md
    - blog/随笔/HTTP.md
    - blog/随笔/会话跟踪技术.md
    - blog/随笔/Spring-Security登录校验机制.md
    - blog/随笔/SQL外键约束与连接.md
    - blog/随笔/Element-Plus组件详细介绍.md
    - blog/随笔/SpringAOP.md
    - blog/随笔/mermaid绘图语法总结.md
    - blog/随笔/Transformer.md
    - blog/随笔/SpringBoot原理篇.md
    - blog/随笔/JavaHttpServeletRequest.md
    - blog/随笔/正则表达式.md
      
    
  - 每日诗词:
    - blog/每日诗词/虞美人·玉阑干外清江浦.md
    - blog/每日诗词/菩萨蛮·回文夏闺怨.md
    - blog/每日诗词/清平乐·六盘山.md
    - blog/每日诗词/洞仙歌·咏柳.md
    - blog/每日诗词/秋兴八首·其一.md
    - blog/每日诗词/与史郎中钦听黄鹤楼上吹笛.md
    - blog/每日诗词/夏日南亭怀辛大.md
    - blog/每日诗词/行香子·秋与.md
    - blog/每日诗词/自题金山画像.md
    - blog/每日诗词/一剪梅·红藕香残玉簟秋.md
    - blog/每日诗词/初到黄州.md
    - blog/每日诗词/雨霖铃·寒蝉凄切.md
    - blog/每日诗词/破阵子·四十年来家国.md
    - blog/每日诗词/春日醉起言志.md
    - blog/每日诗词/峨眉山月歌送蜀僧晏入中京.md
    - blog/每日诗词/三五七言.md
    - blog/每日诗词/木兰花·拟古决绝词柬友.md
    - blog/每日诗词/桃花庵歌.md
    - blog/每日诗词/渔家傲·反第一次大围剿.md
    - blog/每日诗词/青玉案·元夕.md
    - blog/每日诗词/浣溪沙·谁念西风独自凉.md
    - blog/每日诗词/声声慢·寻寻觅觅.md
    - blog/每日诗词/虞美人·听雨.md
    - blog/每日诗词/青玉案·凌波不过横塘路.md
    - blog/每日诗词/相见欢·林花谢了春红.md
    - blog/每日诗词/临江仙·梦后楼台高锁.md
    - blog/每日诗词/题都城南庄.md
    - blog/每日诗词/浪淘沙令·帘外雨潺潺.md
    - blog/每日诗词/鹧鸪天·代人赋.md
    - blog/每日诗词/水仙子·夜雨.md
    - blog/每日诗词/唐多令·惜别.md
    - blog/每日诗词/浪淘沙·把酒祝东风.md
    - blog/每日诗词/临安春雨初霁.md
    - blog/每日诗词/蝶恋花·春景.md
    - blog/每日诗词/喜迁莺·梅雨霁.md
    - blog/每日诗词/梅花引·荆溪阻雪.md
  - 发疯:
    - blog/发疯.md
  - 长期主义:
    - about/fitness.md

  - 关于:
      - 作者个人简介: about/geren.md
      - 个人简历: about/简历.md
      - 支持作者: about/zcw.md
      - 功能测试: about/test.md


copyright: Copyright &copy; gzh # 左下角的版权声明

extra:
  mathjax: true
  alternate:
    - name: 简体中文
      link: /
      # https://wcowin-work.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp
      lang: zh   
    - name: English
      link: /Mkdocs-Wcowin/en/
      # https://wcowin-work.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp
      lang: en
    - name: China(TW)
      link: /Mkdocs-Wcowin/ZH-TW/
      # https://wcowin-work.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=zh-TW&_x_tr_hl=zh-CN&_x_tr_pto=wapp
      lang: zh-TW
  generator: true #是否删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/weixin
      link: https://cdn.jsdelivr.net/gh/Gongzihang6/Pictures@main/Medias/%E6%88%91%E7%9A%84%E5%BE%AE%E4%BF%A1%E4%BA%8C%E7%BB%B4%E7%A0%81.png
      name: Wechat
    - icon: fontawesome/brands/telegram
      link: https://t.me/gongzihang
      name: telegram
    - icon: fontawesome/brands/x-twitter #联系方式图标 : https://fontawesome.com/ 去这里找图标
      link: https://twitter.com/ZihangGong28792
    - icon: fontawesome/brands/github
      link: https://github.com/Gongzihang6

    - icon: fontawesome/regular/envelope #联系方式图标
      link: mailto:<zihanggong24@gmail.com> #邮件联系方式
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/688234000/lists
  analytics:
    provider: google #谷歌分析
    property: G-40HC6RYSR1 ##如果你 clone 了my模板，请将这个修改为你的

    # 网页底部反馈
    feedback:
      title: 此页面有帮助吗？
      ratings:
        - icon: material/thumb-up-outline #图标可自定义
          name: This page was helpful
          data: 1
          note: >-
            谢谢你的反馈！
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  # cookies设置（可选）
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
  #     如果你同意,你可以帮助我们让我们的网站更好

plugins:

  # - ai-summary:
  #     cache_enabled: true              # 启用缓存
  #     cache_expire_days: 300            # 缓存300天
  #     clear_cache: false               # 保留现有缓存
  # - exclude:
  #     glob:
  #       - blog/Computer Science/Algorithm/docs/*
  - search #搜索配置
  # - glightbox:
  #     enabled: !ENV [glightbox, false]
  #     touchNavigation: true
  #     loop: false
  #     effect: fade
  #     slide_effect: slide
  #     width: 100%
  #     height: auto
  #     zoomable: true
  #     draggable: true
  #     skip_classes:
  #       - custom-skip-class-name
  #     auto_caption: false
  #     caption_position: bottom
  #     background: white
  #     shadow: true
  #     manual: false
  - git-committers:
      enabled: !ENV [CI, false]
      repository: Gongzihang6/Discussion
      branch: main
      exclude:
        - index.md
        - tag.md
        - liuyanban.md
        - blog/posts/update.md
        - blog/posts/wkw.md
        - about/link.md
  # - git-revision-date-localized:
  #     # enabled: !ENV [CI, false]
  #     # type: iso_date
  #     # enable_creation_date: false

  #     type: timeago #时间类型
  #     custom_format: "%d. %B %Y"  # 时间格式
  #     timezone: Europe/Amsterdam #时区
  #     locale: en #首选语言
  #     fallback_to_build_date: false #许回退到git 不可用时mkdocs build执行的时间
  #     enable_creation_date: true #是否启用创建时间
  #     exclude:  #排除的页面
  #         - index.md
  #     enabled: true #是否启用
  #     strict: true
  #     exclude:
  #       # - index.md
  #       - tag.md
  #       - liuyanban.md
  #       - blog/posts/update.md
  #       - blog/posts/wkw.md
  #       - about/link.md
  #       - websitebeauty/linktech.md

  - document-dates:
      position: bottom            # 显示位置：top（标题后） bottom（文档末尾），默认：bottom
      type: date               # 时间类型：date datetime timeago，默认：date
      locale: zh               # 本地化语言：en zh zh_TW es fr de ar ja ko ru，默认：en
      date_format: '%Y-%m-%d'  # 日期格式化字符串，例如：%Y年%m月%d日、%b %d, %Y
      time_format: '%H:%M:%S'  # 时间格式化字符串（仅在 type=datetime 时有效）
      exclude:                 # 排除文件列表，默认为空
        - temp.md              # 排除指定文件
        - private/*            # 排除 private 目录下所有文件，包括子目录
      show_author: true        # 是否显示作者信息，默认：true


  - blog: #博客配置
      post_date_format: full #时间
      draft: true
      draft_if_future_date: true #自动将具有未来日期的帖子标记为草稿
      post_readtime: true
      post_readtime_words_per_minute: 265 #计算帖子的阅读时间时读者每分钟预计阅读的字数
      post_url_format: "{date}/{slug}"
      # categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml" #作者信息
  - tags

markdown_extensions: #详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde




  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      linenums_style: "table"
      auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - markdown.extensions.toc:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  #     permalink: "\ue157"

  - admonition
  - pymdownx.details

  - pymdownx.arithmatex: # latex支持
      generic: true
      
      # block_tag: 'div'  # 强制行间公式用div包裹
      block_syntax:
        - dollar  # 用于 $$...$$
        - begin_end # 用于 \begin{}...\end{}
      # preview: false  # 禁用预览模式避免冲突
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format

        - name: raw_html
          class: raw-html
          # format: !!python/name:pymdownx.superfences.fence_raw_format


        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
        # - pymdownx.tabbed:
        #     alternate_style: true

extra_javascript:
  - javascripts/extra.js
  - javascripts/config_mathjax.js  # 确保此文件正确配置了 MathJax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/简历.js
extra_css:
  - stylesheets/extra.css
  - stylesheets/extra2.css
  - stylesheets/简历.css
  # - https://cdn.jsdelivr.net/gh/Wcowin/Mkdocs-Wcowin@main/docs/stylesheets/extra.css
  # - stylesheets/link.css #友链配置
  - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/stylesheets/link.css  #友链CDN
  - stylesheets/customize.css # 搜索圆角优化
  # - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/stylesheets/customize.css  #按钮圆角化CDN
  # - assets/stylesheets/portfolio.css
  # - stylesheets/video.css #播放器可选配置
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css #gitalk支持
  # - ckplayer/css/ckplayer.css   #播放器配置
  # - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css # font-awesome表情支持
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css  #分享支持
  - https://fonts.googleapis.com/css2?family=Klee+One&family=LXGW+WenKai+TC&display=swap
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css #字体
  # - https://static.zeoseven.com/zsft/292/main/result.css #字体
  # - stylesheets/ziti.css  #字体

  - https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@400;600&display=swap
  - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/stylesheets/ziti.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css  #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css  #字体


hooks:
  - docs/overrides/hooks/socialmedia.py
  - docs/overrides/hooks/reading_time.py
  - docs/overrides/hooks/ai_summary.py
  # - docs/overrides/hooks/ai_summary.pysite_name: gzh
site_url: https://gongzihang6.github.io/
site_author: gzh

